# Generated by Django 2.0.3 on 2018-04-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('overview', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('original_title', models.CharField(max_length=150)),
                ('original_language', models.CharField(max_length=150)),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('backdrop_path', models.CharField(max_length=150, null=True)),
                ('poster_path', models.CharField(max_length=150, null=True)),
                ('release_date', models.DateField()),
                ('genres', models.CharField(max_length=150)),
                ('is_adult', models.BooleanField()),
                ('is_video', models.BooleanField()),
            ],
        ),
    ]
