# Generated by Django 2.0.3 on 2018-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default='', max_length=150),
        ),
    ]
