# Generated by Django 2.0.3 on 2018-03-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(max_length=50, unique=True)),
                ('primary_title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('is_adult', models.BooleanField(default=False)),
                ('start_year', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('runtime_minutes', models.IntegerField(null=True)),
                ('genres', models.ManyToManyField(to='imdb.Genre')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nconst', models.CharField(max_length=50, unique=True)),
                ('primary_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField(null=True)),
                ('death_year', models.IntegerField(null=True)),
                ('known_for_titles', models.ManyToManyField(to='imdb.MovieTitle')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='primary_profession',
            field=models.ManyToManyField(to='imdb.Profession'),
        ),
        migrations.AddField(
            model_name='movietitle',
            name='title_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imdb.TitleType'),
        ),
    ]
