# Generated by Django 2.0.3 on 2018-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietitle',
            name='original_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='movietitle',
            name='primary_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='primary_name',
            field=models.CharField(max_length=150),
        ),
    ]
