# Generated by Django 2.0.3 on 2018-03-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20180326_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='movietitle',
            name='title_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.TitleType'),
        ),
        migrations.AddField(
            model_name='principal',
            name='movie_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.MovieTitle'),
        ),
        migrations.AddField(
            model_name='principal',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Profession'),
        ),
        migrations.AddField(
            model_name='character',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='imdb.Principal'),
        ),
    ]
