# Generated by Django 2.0.3 on 2018-04-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_auto_20180327_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietitle',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='movietitle',
            name='number_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='job',
            field=models.CharField(default='', max_length=150),
        ),
    ]
