# Generated by Django 2.0.3 on 2018-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0004_auto_20180410_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Pricipal Category', 'verbose_name_plural': 'Pricipal Categories'},
        ),
        migrations.AlterField(
            model_name='movietitle',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
