# Generated by Django 2.0.3 on 2018-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0005_auto_20180410_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='principal',
        ),
        migrations.AddField(
            model_name='principal',
            name='characters',
            field=models.ManyToManyField(to='imdb.Character'),
        ),
    ]
