# Generated by Django 2.0.3 on 2018-04-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0006_auto_20180410_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Person'),
        ),
    ]
