# Generated by Django 2.0.3 on 2018-04-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0007_auto_20180410_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='characters',
        ),
        migrations.AddField(
            model_name='principal',
            name='characters',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
