# Generated by Django 2.0.3 on 2018-04-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0008_auto_20180410_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Principal Category', 'verbose_name_plural': 'Principal Categories'},
        ),
    ]
