# Generated by Django 2.0.3 on 2018-06-06 12:19

from django.db import migrations


def clear_out_remakes(apps, schema_editor):

    Remake = apps.get_model('remake', 'Remake')
    Remake.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0009_auto_20180418_1636'),
    ]

    operations = [
        migrations.RunPython(clear_out_remakes),
    ]
