# Generated by Django 2.0.3 on 2018-06-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0010_auto_20180606_1219'),
        ('remake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remake',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remake',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='imdb.MovieTitle'),
            preserve_default=False,
        ),
    ]
