# Generated by Django 2.0.3 on 2018-06-06 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def clear_out_remakes(apps, schema_editor):

    Remake = apps.get_model('remake', 'Remake')
    Remake.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remake', '0002_auto_20180606_1357'),
    ]

    operations = [
        migrations.RunPython(clear_out_remakes),
        migrations.AddField(
            model_name='remake',
            name='user',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
