# Generated by Django 2.0.3 on 2018-06-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remake', '0003_remake_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=150)),
                ('actor_name', models.CharField(max_length=150)),
                ('tmdb_profile_path', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='remake',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='remake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remake.Remake'),
        ),
    ]
