# Generated by Django 2.0.3 on 2018-06-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0009_auto_20180418_1636'),
        ('remake', '0004_auto_20180615_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='imdb_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imdb.Principal'),
        ),
        migrations.AddField(
            model_name='character',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='remake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='remake.Remake'),
        ),
    ]
