# Generated by Django 2.0.3 on 2018-06-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remake', '0005_auto_20180616_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='remake',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
