# Generated by Django 2.0.3 on 2018-06-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remake', '0006_remake_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
